### ISSUE TITLE
Problem podczas próby instalacji przez composer.

### ISSUE THREAD

**Issue by damianpudlo** [WebUltd/WebUltdPayUPaymentBundle#4]
Używam Symfony 2.1
W app kernel mam:

public function registerBundles() {
        $bundles = array(
            ...
            new webultd\Payu\PaymentBundle\webultdPayuPaymentBundle()

```
    );
```

}

Composer wszystko poprawnie ściąga (nie wyrzuca żadnych błędów).

Niestety w przeglądarce oraz w cli (np. podczas uruchamiania assets:install) wyrzuca błąd:

Fatal error: Class 'webultd\Payu\PaymentBundle\webultdPayuPaymentBundle' not found in C:\xampp\htdocs\mysite\trunk\app\AppKernel.php on line 37

**Comment by phpeek** [comment]
Mój błąd. Naprawiłem problem, ale nie wiem ile czasu potrwa akceptacja mojego pull request-a - https://github.com/WebUltd/WebUltdPayUPaymentBundle/pull/5, więc tymczasowo możesz korzystać z mojej gałęzi - https://github.com/dyferencjal/WebUltdPayUPaymentBundle.  Dodałem też pakiet do packagist-a - w composerze, w sekcji require podaj: - "dyferencjal/webultdpayupaymentbundle": "dev-master".

**Comment by tscislo** [comment]
Po dodaniu do głównego composer.json:
"dyferencjal/webultdpayupaymentbundle": "dev-master"

Otrzymuje taki błąd po wydaniu polecenia composerowi do instalacji:

  Problem 1
    - symfony/framework-bundle 2.0.7 requires symfony/translator 2.0.7 -> no matching package found.
    - Conclusion: remove symfony/symfony v2.2.0
    - Conclusion: don't install symfony/symfony v2.2.0
    - Conclusion: don't install symfony/symfony v2.2.0-RC3
    - Conclusion: don't install symfony/symfony v2.2.0-RC2
    - Installation request for dyferencjal/webultdpayupaymentbundle dev-master -> satisfiable by dyferencjal/webultdpayupaymentbundle dev-master.
    - Conclusion: don't install symfony/symfony v2.2.0-RC1
    - Conclusion: don't install symfony/symfony v2.2.0-BETA2
    - dyferencjal/webultdpayupaymentbundle dev-master requires symfony/framework-bundle >=2.0,<2.2-dev -> satisfiable by symfony/symfony 2.0.7, symfony/symfony v2.0.10, symfony/symfony v2.0.11, symfony/symfony v2.0.12, symfony/symfony v2.0.13, symfony/symfony v2.0.14, symfony/symfony v2.0.15, symfony/symfony v2.0.16, symfony/symfony v2.0.17, symfony/symfony v2.0.18, symfony/symfony v2.0.19, symfony/symfony v2.0.20, symfony/symfony v2.0.21, symfony/symfony v2.0.22, symfony/symfony v2.0.23, symfony/symfony v2.0.9, symfony/symfony v2.1.0, symfony/symfony v2.1.0-BETA1, symfony/symfony v2.1.0-BETA2, symfony/symfony v2.1.0-BETA3, symfony/symfony v2.1.0-BETA4, symfony/symfony v2.1.0-RC1, symfony/symfony v2.1.0-RC2, symfony/symfony v2.1.1, symfony/symfony v2.1.2, symfony/symfony v2.1.3, symfony/symfony v2.1.4, symfony/symfony v2.1.5, symfony/symfony v2.1.6, symfony/symfony v2.1.7, symfony/symfony v2.1.8, symfony/symfony v2.1.9, symfony/framework-bundle 2.0.7, symfony/framework-bundle v2.0.10, symfony/framework-bundle v2.0.12, symfony/framework-bundle v2.0.13, symfony/framework-bundle v2.0.14, symfony/framework-bundle v2.0.15, symfony/framework-bundle v2.0.16, symfony/framework-bundle v2.0.17, symfony/framework-bundle v2.0.18, symfony/framework-bundle v2.0.19, symfony/framework-bundle v2.0.20, symfony/framework-bundle v2.0.21, symfony/framework-bundle v2.0.22, symfony/framework-bundle v2.0.23, symfony/framework-bundle v2.0.9, symfony/framework-bundle v2.1.0, symfony/framework-bundle v2.1.0-BETA1, symfony/framework-bundle v2.1.0-BETA2, symfony/framework-bundle v2.1.0-BETA3, symfony/framework-bundle v2.1.0-BETA4, symfony/framework-bundle v2.1.0-RC1, symfony/framework-bundle v2.1.0-RC2, symfony/framework-bundle v2.1.1, symfony/framework-bundle v2.1.2, symfony/framework-bundle v2.1.3, symfony/framework-bundle v2.1.4, symfony/framework-bundle v2.1.5, symfony/framework-bundle v2.1.6, symfony/framework-bundle v2.1.7, symfony/framework-bundle v2.1.8, symfony/framework-bundle v2.1.9.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony 2.0.7.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.10.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.11.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.12.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.13.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.14.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.15.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.16.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.17.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.18.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.19.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.20.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.21.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.22.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.23.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.0.9.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.0.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.0-BETA1.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.0-BETA2.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.0-BETA3.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.0-BETA4.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.0-RC1.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.0-RC2.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.1.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.2.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.3.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.4.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.5.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.6.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.7.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.8.
    - Can only install one of: symfony/symfony v2.2.0-BETA1, symfony/symfony v2.1.9.
    - don't install symfony/framework-bundle v2.1.0|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.0-BETA1|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.0-BETA2|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.0-BETA3|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.0-BETA4|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.0-RC1|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.0-RC2|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.1|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.2|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.3|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.4|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.5|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.6|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.7|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.8|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.1.9|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.0.10|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.0.12|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.0.13|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.0.14|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.0.15|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.0.16|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.0.17|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.0.18|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.0.19|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.0.20|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.0.21|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.0.22|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.0.23|don't install symfony/symfony v2.2.0-BETA1
    - don't install symfony/framework-bundle v2.0.9|don't install symfony/symfony v2.2.0-BETA1
    - Installation request for symfony/symfony 2.2.\* -> satisfiable by symfony/symfony v2.2.0, symfony/symfony v2.2.0-BETA1, symfony/symfony v2.2.0-BETA2, symfony/symfony v2.2.0-RC1, symfony/symfony v2.2.0-RC2, symfony/symfony v2.2.0-RC3.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Macie jakieś pomysły?

**Comment by phpeek** [comment]
Prawdopodobnie problemem są nieaktualne dependencje composer-a. Napisz do której wersji Symfony chcesz doinstalować bundle.

**Comment by phpeek** [comment]
Dopiero teraz zauważyłem, że mowa o Symfony 2.0.0. W jakis sposób zorganizowałeś doinstalowywanie vendorów przez composer-a ? Symfony wspiera composer-a od > 2.1

**Comment by tscislo** [comment]
Cześć,

Chodziło oczywiście o Symfony 2.2.0 - mój błąd. Na szczęście Bundle działa na tej wersji kiedy go ręcznie dograłem, problemy są tylko z zainstalowaniem i pewnie jest tak jak napisałeś w 1szej wiadomości.

Dodatkowo mam pytanie o to jak używać tego Bundle, bo nie ma nigdzie wyczerpującej instrukcji. Np. chodzi mi o to jak w ogóle zainicjować z jego użyciem płatność. Nie widze niestety akcji która mogłaby na to pozwolić? Czy mógłbyś opisać mi flow korzystania z tego Bundle?

Tomek

**Comment by phpeek** [comment]
Obawiam się, że na to nie starczy mi czasu do weekend-u. Workflow podyktowany jest biblioteką openpayu_php. Przykład wykorzystania jest tutaj - https://github.com/PayU/openpayu_php_example. Wszystkie kroki zamieszczone w tym przykładzie znajdziesz jako akcje w kontrolerze PaymentController. Kontroler traktowałbym jako przykład, a wykorzystywał tylko serwisy, które w kontenerze stworzy bundle - webultd_payu_payment.api, 
webultd_payu_payment.shopping_cart. Ponadto do wykorzystania jest rozszerzenie twig-a, które wprowadza metodę {{ renderPayuButton() }}, do renderowania formularza płatności. Wiem, że to skomplikowane. Śpieszysz się z tym bardzo ? Postaram się przysiąść do czegoś, co choć trochę mogłoby przypominać manual ;)  

Błażej chyba porzucił projekt... :(

Gdybyś chciał pomóc rozwijać bundle to zapraszam do mnie, bo Błażej nie akceptuje już PR - mój wisi od dłuuuuuższego czasu ;)

**Comment by phpeek** [comment]
Naprawiłem błąd z instalacją przez composer-a.

**Comment by tscislo** [comment]
Dzięki za poprawkę.

Spiesze się, a aktualnie nie jestem w stanie nawet wystartować z używaniem tego Bundle. Skonfigurowałem wszystko tak jak jest opisane na github, ale manuala tam nie ma. 

Patrzyłem właśnie na przykład z https://github.com/PayU/openpayu_php_example i niestety w PaymentController widze tylko 6 akcji z których na pewno żadna nie służy do inicializacji płatności.

Dodatkowo nie rozumiem tego: "Kontroler traktowałbym jako przykład, a wykorzystywał tylko serwisy, które w kontenerze stworzy bundle - webultd_payu_payment.api,
webultd_payu_payment.shopping_cart." ?

Jeśli chodzi o rozszerzenie do twig to też poprosiłbym o jakiś opis. 

Jeśli udałoby ci się przygotować manual do weekendu to będzie super.

Tomek

**Comment by phpeek** [comment]
Do weekendu nie ma szans. W weekend bym do tego usiadł. Niestety, ale jestem na etacie, więc nie bardzo jestem w stanie w tygodniu się na tym skupić.

**Comment by tscislo** [comment]
Jakby udało ci się w weekend coś napisać to też będzie super.
Na tym etapie fajnie jakbyś dał znać w jaki sposób z użyciem rego Bundle zainicjować płatność - potem będę sam walczył.

**Comment by bgruszka** [comment]
Ok, wróciłem do życia ;) Próba instalacji przechodzi więc zamykam to issue.
